#lang racket
;; (actualizar '("a" "b" "r") '(0 0 0 0))
(define(actualizar list1 listnum)
  (cond((equal? (contar list1) 1) (list (actualizar_aux list1) (list (car listnum) (cadr listnum)) '(0 0) '(("B1" "C1") ("D1" "E1")) '("cartas") 1))
       ((equal? (contar list1) 2) (list (actualizar_aux list1) (list (car listnum) (cadr listnum) (caddr listnum)) '(0 0 0) '(("B2" "C2") ("D2" "E2") ("F2" "G2")) '("cartas") 2))
       (else (list (actualizar_aux list1) (list (car listnum) (cadr listnum) (caddr listnum) (cadddr listnum)) '(0 0 0 0) '(("B3" "C3") ("D3" "E3") ("F3" "G3") ("H3" "I3")) '("cartas") 3))
       ))

(define(actualizar_aux list1)
  (cond((null? list1) '("Crupier"))
       ((equal?  (car list1) "-") (actualizar_aux (cdr list1)))
       (else (cons (car list1) (actualizar_aux (cdr list1))))
       ))

(define(contar list1)
  (cond((null? list1) 0)
       ((equal? (car list1) "-") (+ 0 (contar (cdr list1))))
       ((equal? (car list1) "Crupier") (+ 0 (contar (cdr list1))))
       (else (+ 1 (contar (cdr list1))))
       ))

;; (mayor(caddr(actualizar '("a" "b" "r"))))
(define(mayor lista)
  (cond((null? lista) '())
       (else (mayor_aux (car lista) (cdr lista)))
       ))
(define(mayor_aux ele lista)
  (cond((null? lista) ele)
       ((< ele (car lista)) (mayor_aux (car lista) (cdr lista)))
       (else (mayor_aux ele (cdr lista)))
       ))
(define (eliminate_aux list1 num)
  (cond((equal? num 0) (cdr list1))
       (else (cons (car list1) (eliminate_aux (cdr list1) (- num 1))))
       ))
;;(eliminate (actualizar '("a" "b" "r")) 1)
(define(eliminate list1 num)
  (list (eliminate_aux(car list1) num) (eliminate_aux(cadr list1)num) (eliminate_aux(caddr list1)num) (cadddr list1) (car(cddddr list1)) (cadr(cddddr list1))))

;; (winner '(("Crupier" 17 "No" 1) ("a" 0 "No" 1) ("b" 0 "No" 1) ("r" 0 "No" 1)) 1)
(define(winner list1 num)
  (cond((equal? num 0) list1)
       ((< 21 (cadar list1)) (cons (car list1) (winner (cdr list1) num)))
       (else (cons (list (caar list1) (cadar list1) "Yes" (+ 1 (car(cdddar list1)))) (winner (cdr list1) 0)))
       ))

;; (table (actualizar '("a" "b" "c") '(0 0 0 0)))
(define(table list1)
  (append (list (cadr(cddddr list1))) (winner(table_aux list1 (mayor (caddr list1)))1) (list(car list1))))

(define(table_aux list1 max)
  (cond((null? max) '())
       ((equal? max (caaddr list1)) (cons (list (caar list1) (caaddr list1) "" (caadr list1))
                                          (table_aux (eliminate list1 0) (mayor (eliminate_aux(caddr list1) 0)))))
       ((equal? max (car (cdaddr list1))) (cons(list (cadar list1) (car (cdaddr list1)) "" (cadadr list1))
                                          (table_aux (eliminate list1 1) (mayor (eliminate_aux(caddr list1) 1)))))
       ((equal? max (cadr(cdaddr list1))) (cons(list (caddar list1) (cadr(cdaddr list1)) "" (car(cddadr list1)))
                                          (table_aux (eliminate list1 2) (mayor (eliminate_aux(caddr list1) 2)))))
       ((equal? max (caddr(cdaddr list1))) (cons(list (car(cdddar list1)) (caddr(cdaddr list1)) "" (cadr(cddadr list1)))
                                           (table_aux (eliminate list1 3) (mayor (eliminate_aux(caddr list1) 3)))))
       ))

;; (order 3 '(("Crupier" 17 "Yes" 1) ("a" 0 "" 5) ("b" 0 "" 6) ("c" 0 "" 7) ("a" "b" "c" "Crupier")))

(define(order num list1)
  (cond((equal? num 1) (cond((null? (caddr list1))'())
                            ((equal? (caaddr list1) (caar list1)) (cons (car(cdddar list1)) (order num (list (car list1) (cadr list1) (cdaddr list1)))))
                            (else (cons (cadr(cddadr list1)) (order num (list (car list1) (cadr list1) (cdaddr list1)))))
                            ))
       ((equal? num 2)(cond((null? (car(cdddr list1)))'())
                           ((equal? (caar(cdddr list1)) (caar list1)) (cons (car(cdddar list1)) (order num (list (car list1) (cadr list1) (caddr list1) (cdar(cdddr list1))))))
                           ((equal? (caar(cdddr list1)) (caadr list1)) (cons (cadr(cddadr list1)) (order num (list (car list1) (cadr list1) (caddr list1)  (cdar(cdddr list1))))))
                           (else (cons (caddr(cdaddr list1)) (order num (list (car list1) (cadr list1) (caddr list1)  (cdar(cdddr list1))))))
                           ))
       (else (cond((null? (car(cddddr list1)))'())
                  ((equal? (caar(cddddr list1)) (caar list1)) (cons (car(cdddar list1)) (order num (list (car list1) (cadr list1) (caddr list1) (cadddr list1) (cdar(cddddr list1))))))
                  ((equal? (caar(cddddr list1)) (caadr list1)) (cons (cadr(cddadr list1)) (order num (list (car list1) (cadr list1) (caddr list1) (cadddr list1) (cdar(cddddr list1))))))
                  ((equal? (caar(cddddr list1)) (caaddr list1)) (cons (caddr(cdaddr list1)) (order num (list (car list1) (cadr list1) (caddr list1) (cadddr list1) (cdar(cddddr list1))))))
                  (else (cons (cadddr(cadddr list1)) (order num (list (car list1) (cadr list1) (caddr list1) (cadddr list1) (cdar(cddddr list1))))))
                  ))
       ))

;;===================================================================================================================================
;; (cargar (actualizar '("a" "b" "r") '(0 0 0 0)) 1)
(define (cargar list1 num1)
  (cond((equal? num1 1) (list (car list1) (cadr list1) (append (list (+ 3 (caaddr list1))) (cdaddr list1)) (append (list(append (list "H9") (car(cadddr list1)))) (cdr(cadddr list1))) (car(cddddr list1)) (cadr(cddddr list1))))
       ((equal? num1 2) (list (car list1) (cadr list1) (append (list (caaddr list1) (+ 3 (car(cdaddr list1)))) (cdr(cdaddr list1))) (append (list (car(cadddr list1))) (list(append (list "H9") (cadr(cadddr list1)))) (cddr(cadddr list1))) (car(cddddr list1)) (cadr(cddddr list1))))
       ((equal? num1 3) (list (car list1) (cadr list1) (append (list (caaddr list1) (car(cdaddr list1)) (+ 3 (cadr(cdaddr list1)))) (cddr(cdaddr list1))) (append (list (car(cadddr list1))) (list(cadr(cadddr list1))) (list(append (list "H9") (caddr(cadddr list1)))) (cdddr(cadddr list1))) (car(cddddr list1)) (cadr(cddddr list1))))
       ((equal? num1 4) (list (car list1) (cadr list1) (append (list (caaddr list1) (car(cdaddr list1)) (cadr(cdaddr list1)) (+ 3 (caddr(cdaddr list1)))) (list)) (append (list (car(cadddr list1))) (list(cadr(cadddr list1))) (list(caddr(cadddr list1)))(list(append (list "H9") (cadddr(cadddr list1)))) (list)) (car(cddddr list1)) (cadr(cddddr list1))))
       ))

(provide (all-defined-out))